version: "3.8"

services:
    #portainer:
    #    image: portainer/portainer:1.24.2
    #    restart: always
    #    ports:
    #        - 9009:9000
    #    volumes:
    #        - /var/run/docker.sock:/var/run/docker.sock
    #        - ./data/portainer:/data
    #mysql:
    #    image: mysql:8.0.23
    #    restart: always
    #    environment:
    #        - MYSQL_ROOT_PASSWORD=aA123456!
    #    command: --default-authentication-plugin=mysql_native_password
    #    ports:
    #        - 3306:3306
    #    volumes:
    #        - ./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    #        - ./data/mysql:/var/lib/mysql
    #        - ./conf/mysql/initdb.d:/docker-entrypoint-initdb.d
    #redis:
    #    image: redis:6.2.1-buster
    #    restart: always
    #    ports:
    #        - 6379:6379
    #    volumes:
    #        - ./data/redis:/data
    #        - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    #    command: redis-server /usr/local/etc/redis/redis.conf
    #minio:
    #    image: minio/minio:RELEASE.2021-01-30T00-20-58Z.hotfix.0c1d75aa8
    #    restart: always
    #    environment:
    #        MINIO_ACCESS_KEY: "admin"
    #        MINIO_SECRET_KEY: "12345678"
    #    command: server /data
    #    ports:
    #        - 9000:9000
    #    volumes:
    #        - ./data/minio:/data
    #influxdb:
    #    image: influxdb:1.8.1
    #    restart: always
    #    environment:
    #        TZ: "Asia/Shanghai"
    #        INFLUXDB_ADMIN_ENABLED: "true"
    #        INFLUXDB_ADMIN_USER: admin
    #        INFLUXDB_ADMIN_PASSWORD: admin
    #    ports:
    #        - 8086:8086
    #        - 8088:8088
    #    volumes:
    #        - ./data/influxdb:/var/lib/influxdb
    aspnetwebtemplate:
      image: aspnetwebtemplate
      build:
        context: .
        dockerfile: src/AspNetWebTemplate/Dockerfile
